/**
 * Rule Export — convert lgtm rules into upstream enforcement mechanisms.
 *
 * Supports:
 *   hook     → git pre-commit hook script
 *   steering → .kiro/steering/ markdown for AI agents
 *   eslint   → ESLint no-restricted-syntax config
 */

import type { Rule } from "./rules.js";

/**
 * Export rules as a git pre-commit hook script.
 * Regex rules become grep checks; LLM rules become lgtm scan calls.
 */
export function exportAsHook(rules: Rule[]): string {
  const lines = [
    "#!/bin/sh",
    "# Generated by lgtm — do not edit manually",
    "# Re-generate with: lgtm review rule export --format hook",
    "#",
    "# This hook checks staged files against lgtm review rules.",
    "",
    'echo "👍 lgtm pre-commit check..."',
    "",
    "ERRORS=0",
    "",
  ];

  const regexRules = rules.filter((r) => r.enabled && r.enforcement === "regex" && r.pattern);

  for (const rule of regexRules) {
    const fileFilter = rule.filePattern
      ? `--include='${globToGitGrep(rule.filePattern)}'`
      : "";

    lines.push(`# Rule: ${rule.description} [${rule.id}]`);
    lines.push(
      `if git diff --cached --name-only ${fileFilter} | xargs grep -lE '${escapeShell(rule.pattern!)}' 2>/dev/null; then`
    );
    lines.push(`  echo "  ✗ ${rule.severity}: ${rule.description}"`);
    if (rule.severity === "error") {
      lines.push("  ERRORS=$((ERRORS + 1))");
    }
    lines.push("fi");
    lines.push("");
  }

  // LLM rules: delegate to lgtm scan
  const llmRules = rules.filter((r) => r.enabled && r.enforcement === "llm");
  if (llmRules.length > 0) {
    lines.push("# LLM rules — delegated to lgtm scan (requires AI)");
    for (const rule of llmRules) {
      lines.push(`# lgtm review scan --rule ${rule.id}  # ${rule.description}`);
    }
    lines.push("");
  }

  lines.push('if [ "$ERRORS" -gt 0 ]; then');
  lines.push('  echo ""');
  lines.push('  echo "  ✗ $ERRORS error(s) found. Commit blocked."');
  lines.push('  echo "  Run: lgtm review scan for details"');
  lines.push("  exit 1");
  lines.push("fi");
  lines.push("");
  lines.push('echo "  ✓ All checks passed"');
  lines.push("");

  return lines.join("\n");
}

/**
 * Export rules as .kiro/steering markdown for AI agents.
 */
export function exportAsSteering(rules: Rule[]): string {
  const lines = [
    "# Code Review Rules",
    "",
    "These rules are enforced by lgtm during code review.",
    "Please follow them when generating or modifying code.",
    "",
    "---",
    "",
  ];

  for (const rule of rules.filter((r) => r.enabled)) {
    lines.push(`## ${rule.description}`);
    lines.push("");
    lines.push(`- **Category:** ${rule.category}`);
    lines.push(`- **Severity:** ${rule.severity}`);
    if (rule.filePattern) lines.push(`- **Applies to:** \`${rule.filePattern}\``);
    lines.push("");

    if (rule.examples.bad.length > 0) {
      lines.push("### ❌ Don't do this:");
      lines.push("");
      for (const ex of rule.examples.bad) {
        lines.push("```", ex, "```");
      }
      lines.push("");
    }

    if (rule.examples.good.length > 0) {
      lines.push("### ✅ Do this instead:");
      lines.push("");
      for (const ex of rule.examples.good) {
        lines.push("```", ex, "```");
      }
      lines.push("");
    }

    lines.push("---", "");
  }

  return lines.join("\n");
}

/**
 * Export regex rules as ESLint config (with limitations).
 *
 * NOTE: ESLint's no-restricted-syntax uses AST selectors, not regex patterns.
 * This export provides the rule metadata and patterns as documentation,
 * but cannot directly enforce regex patterns via ESLint.
 *
 * For actual regex enforcement in ESLint, use eslint-plugin-regexp or
 * keep using the lgtm git hook export (--format hook) which uses grep.
 */
export function exportAsESLint(rules: Rule[]): string {
  const regexRules = rules.filter(
    (r) => r.enabled && r.enforcement === "regex" && r.pattern
  );

  const eslintRules: Array<{ selector: string; message: string }> = [];

  for (const rule of regexRules) {
    eslintRules.push({
      selector: `// Pattern: ${rule.pattern}`,
      message: `[${rule.severity}] ${rule.description} (lgtm rule: ${rule.id})`,
    });
  }

  const config = {
    _WARNING: "This config cannot enforce regex patterns via ESLint. Use 'lgtm review rule export --format hook' for regex enforcement, or install eslint-plugin-regexp.",
    rules: {
      "no-restricted-syntax": [
        "warn",
        ...eslintRules,
      ],
    },
    _lgtmMetadata: {
      generated: new Date().toISOString(),
      exportFormat: "eslint",
      limitation: "ESLint no-restricted-syntax uses AST selectors, not regex. Patterns below are for reference only.",
      recommendation: "Use --format hook for grep-based enforcement, or eslint-plugin-regexp for ESLint-native regex checking.",
      rules: regexRules.map((r) => ({
        id: r.id,
        description: r.description,
        pattern: r.pattern,
      })),
    },
  };

  return JSON.stringify(config, null, 2);
}

// ─── Helpers ────────────────────────────────────────────────────────────

function escapeShell(s: string): string {
  return s.replace(/'/g, "'\\''");
}

function globToGitGrep(glob: string): string {
  // Convert **/*.ts to *.ts for git grep --include
  return glob.replace(/\*\*\//g, "");
}
